Fabricantes (#CNPJ, nome, rua, nro, bairro)
Produtos(#numero, nomeComercial, tipoEmbalagem, precoUnitario, qntLote, #&CNPJ)
Medicamentos(#&numProduto, tarja, formula)
Perfumes(#&numProduto, sexo, intensidade)
ReceitasMedicas(#nroReceita, CRMMedico, data)
Vendas(#nroNota, data, nomeCliente)
Emails(#&nroNota, #email)
Estetica(#&numProduto, #&nroNota, quantidade, imposto)
Tratamentos(quantidade, imposto, #&nrReceita, #&nroNota, #&nrProduto)
